/** Frontend mirrors of backend PermissionNames (do not change backend). */
export const PermissionNames = {
    Tenants: 'Pages.Tenants',
    Users: 'Pages.Users',
    Roles: 'Pages.Roles',
    Categories: 'Pages.Categories',
    Brands: 'Pages.Brands',
    Branches: 'Pages.Branches',
    BranchesApprove: 'Pages.Branches.Approve',
    Units: 'Pages.Units',
    Products: 'Pages.Products',
    Customers: 'Pages.Customers',
    Staff: 'Pages.Staff',
    StaffAttendance: 'Pages.StaffAttendance',
    StaffAttendanceCreate: 'Pages.StaffAttendance.Create',
    StaffAttendanceEdit: 'Pages.StaffAttendance.Edit',
    StaffAttendanceDelete: 'Pages.StaffAttendance.Delete',
    StaffPayroll: 'Pages.StaffPayroll',
    StaffPayrollCreate: 'Pages.StaffPayroll.Create',
    StaffPayrollEdit: 'Pages.StaffPayroll.Edit',
    StaffPayrollDelete: 'Pages.StaffPayroll.Delete',
    Suppliers: 'Pages.Suppliers',
    Accounts: 'Pages.Accounts',
    LedgerEntries: 'Pages.LedgerEntries',
    Purchases: 'Pages.Purchases',
    Sales: 'Pages.Sales',
    StockAdjustments: 'Pages.StockAdjustments',
    Expenses: 'Pages.Expenses',
    Reports: 'Pages.Reports',
    CustomerOrders: 'Pages.CustomerOrders',
    EmailTemplates: 'Pages.EmailTemplates',
    LookUps: 'Pages.LookUps',
} as const;
